# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Mothra-iOS' do
  source 'https://github.com/CocoaPods/Specs.git'
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Mothra',  :path => '../'

end
